version: "3.8"

services:
  minio-s3:
    build:
      context: .
      dockerfile: ./minio/Dockerfile
    container_name: minio-s3
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_pswd
    command: server /data --console-address ":9001"
    volumes:
      - "minio_s3_data:/data"

volumes:
  minio_s3_data:
